# Dependencies
markdown:         kramdown
highlighter:      rouge

# Gems
plugins: [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            Arvind Rao
tagline:          'Mathematician / Software Engineer'
description:      'Mathematician / Software Engineer. <a href="https://twitter.com/cwcomplex" target="_blank">@cwcomplex</a>.'
url:

author:
  name:           'Arvind Rao'
  url:            https://twitter.com/{{ site.data.theme.social.twitter }}
  cv:             /assets/resume_for_web.pdf
  linkedin:       http://www.linkedin.com/in/"{{ site.data.theme.social.linkedin }}"

paginate:         8

# Custom vars
#version:          

github:
  repo:           https://github.com/{{ site.data.theme.social.github }}
