# Dependencies
markdown:         kramdown
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Arvind Rao
tagline:          'Mathematician / Image Scientist / Software Engineer'
description:      'Mathematician / Image Scientist / Software Engineer. <a href="https://twitter.com/arvindsnotes" target="_blank">@arvindsnotes</a>.'
url:              http://hyd

author:
  name:           'Arvind Rao'
  url:            https://twitter.com/arvsrao

paginate:         3

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/arvsrao