# Dependencies
markdown:         kramdown
highlighter:      rouge

# Gems
gems: [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            Arvind Rao
tagline:          'Mathematician / Software Engineer'
description:      'Mathematician / Software Engineer. <a href="https://twitter.com/6sphere" target="_blank">@6sphere</a>.'
url:              

author:
  name:           'Arvind Rao'
  url:            https://twitter.com/6sphere
  cv:             /assets/resume_for_web.pdf
  linkedin:       http://www.linkedin.com/in/asrao

paginate:         3

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/arvsrao
